"""empty message

Revision ID: b38c7859f209
Revises: c105572f2f97
Create Date: 2018-02-07 13:21:12.799819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38c7859f209'
down_revision = 'c105572f2f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'recipes', ['recipe_id'], ['id'])
    op.drop_column('users', 'recipes_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recipes_id', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'recipe_id')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
